import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// Release signing material. Configured by keystore.properties at the repo root;
// see keystore.properties.example for the template. Both the properties file and
// the .jks it points at are gitignored -- if they are missing the release build
// still works, it just comes out unsigned.
val keystoreProps = Properties().apply {
    val f = rootProject.file("keystore.properties")
    if (f.exists()) FileInputStream(f).use { load(it) }
}

// A half-configured keystore (properties present, .jks missing or a blank
// password) would fail the build with an opaque signing error deep inside AGP.
// Detect it here and fall back to an unsigned release instead.
val releaseStore = keystoreProps.getProperty("storeFile")?.let { rootProject.file(it) }
val hasReleaseKey = keystoreProps.isNotEmpty() &&
    releaseStore?.let { it.exists() } == true &&
    !keystoreProps.getProperty("storePassword").isNullOrBlank() &&
    !keystoreProps.getProperty("keyPassword").isNullOrBlank()

android {
    namespace = "org.dpdns.mattsgateway.sshwithtailscale"
    compileSdk = 34

    defaultConfig {
        applicationId = "org.dpdns.mattsgateway.sshwithtailscale"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0.0"
    }

    signingConfigs {
        if (hasReleaseKey) {
            create("release") {
                storeFile = releaseStore
                storePassword = keystoreProps.getProperty("storePassword")
                keyAlias = keystoreProps.getProperty("keyAlias")
                keyPassword = keystoreProps.getProperty("keyPassword")
            }
        } else if (keystoreProps.isNotEmpty()) {
            logger.warn(
                "keystore.properties is present but incomplete (missing .jks or blank " +
                    "password) -- building an unsigned release. See keystore.properties.example."
            )
        }
        // The debug keystore AGP would sign debug builds with. Used only by the
        // `selfUse` build type below.
        create("debugKey") {
            val androidHome = System.getenv("ANDROID_USER_HOME")
                ?: "${System.getProperty("user.home")}/.android"
            storeFile = file("$androidHome/debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            if (hasReleaseKey) {
                signingConfig = signingConfigs.getByName("release")
            }
        }

        /**
         * Release build signed with the **debug** key.
         *
         * Android refuses to install an APK whose signing key differs from the
         * installed one, and uninstalling wipes the app's private storage -- which
         * is where the Tailscale login state lives. Signing with the same key as
         * an already-installed debug build allows upgrading in place instead.
         *
         * Kept debuggable on purpose: it is only ever installed on your own
         * phone, and `adb shell run-as` plus the in-app diagnostics both need it.
         * Signing is unaffected, so the in-place upgrade still works.
         *
         * Share `release` instead: the debug key is public, so anyone could
         * forge an update to this variant.
         */
        create("selfUse") {
            initWith(getByName("release"))
            signingConfig = signingConfigs.getByName("debugKey")
            isDebuggable = true
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            // libgojni.so is ~30 MB. Stored uncompressed it makes the APK ~63 MB;
            // compressing it roughly halves the download size.
            useLegacyPackaging = true
        }
    }

    buildFeatures {
        // Used to keep the verbose diagnostics out of release builds.
        buildConfig = true
    }

    testOptions {
        // The integration test drives the real SshSession, which logs through
        // android.util.Log; the stubbed android.jar would otherwise throw
        // "not mocked" for every log line.
        unitTests.isReturnDefaultValues = true
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    // The gomobile-produced AAR is generated by generate_aar.sh / CI into app/libs.
    // It already ships jni/<abi>/libgojni.so, and AGP extracts native libs from
    // AAR dependencies automatically, so no jniLibs.srcDirs override is needed.
    // (Kotlin DSL note: srcDirs is a read-only val, so `srcDirs += ...` does not compile.)
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.24")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    // Material 3 widgets and themes (pulls in AppCompat, which is why the
    // activity is an AppCompatActivity).
    implementation("com.google.android.material:material:1.12.0")
    // Pull-to-refresh for the file-manager list.
    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")
    // SSH client with built-in SOCKS5 proxy support (ProxySOCKS5).
    //
    // This is the maintained fork of com.jcraft:jsch (identical package names,
    // drop-in replacement). Upstream 0.1.55 is from 2018 and cannot authenticate
    // with RSA keys against OpenSSH 8.8+, which disabled the legacy ssh-rsa
    // (SHA-1) signature; the fork adds rsa-sha2-256/512, ed25519 and modern KEX.
    implementation("com.github.mwiede:jsch:0.2.25")
    // lifecycleScope for MainActivity's coroutines (torn down with the Activity).
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    // Unit tests for the (Android-free) terminal buffer logic.
    testImplementation("junit:junit:4.13.2")
    // Real org.json for unit tests: the android.jar the tests run against only
    // has stubs, and ForwardRule's persistence format is worth testing.
    testImplementation("org.json:json:20240303")
    // Tailscale userspace (netstack) binding: local SOCKS5 proxy on 127.0.0.1:1055.
    implementation(files("libs/tailscale.aar"))
}
